// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// The Edge Functions gateway rejects the new publishable key (sb_publishable_...)
// with 401 UNAUTHORIZED_INVALID_JWT_FORMAT. The legacy anon JWT (eyJ...) works for
// both PostgREST and Functions, so prefer it; fall back to the publishable key.
const SUPABASE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ?? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});